### PR TITLE
Yes 13 magento 1 technical review

### PR DESCRIPTION
**Pull request by haroon-chaudhry**

### CODE REVIEW

**Comment by ijazalise** [comment]
There were lot of unwanted code and line breaks which were producing warnings in ECG and MEQP1 Therefore removed that code in that commit.

**Comment by ijazalise** [comment]
Please explain more about what you want with EOF?

**Comment by liebstein** [comment]
EOF is end of file character. It basically means you need to end your files with a blank line

**Comment by haroon-chaudhry** [comment]
This pull request is obsolete now since we have redone the review and package in https://github.com/YotpoLtd/magento-plugin/pull/20.

**Pull request closed without merging**
